refactor/code: make typecasts explicit, remove dead SMS trigger code
opengovsg/plumber pull request #313
Opened 2023-11-06 11:10 UTC by liangyuanruo

## Problem

Some functions in the codebase (namely, `defineAction`, `defineApp`, `defineTrigger`, `dynamicData`) do not perform any computation, but merely return the argument supplied as its return value. This introduces a layer of indirection and increases obscurity to the developer without any benefits.

Separately, dead code for SMS triggers were dangling in the codebase; these were simply deleted.

## Solution

Refactor the codebase to remove the reliance on the above-mentioned functions and files.

2023-11-06 14:43 UTC, ogp-weeloong requested changes
Thanks for this and great to see we're getting better typing into the codebase!

Just need some further changes before this can land:
1. Add twilo to app mapping
2. in `models/app.ts`, migrate the yucky bits with`readdirsync` to use .
3. 

Let's also:
* Regression test a bit more by running the code with some flows; I don't trust our test coverage yet. I found out about missing twilo by executing the code.
  * (Common user use case) formsg -> vault -> if/then -> postman / telegram
  * (Uncommon use case) webhook -> delay -> custom API
* Let's add a test to ensure that all apps in the `apps` folder are declared inside our `app` mapping. This test can make use of `readdirSync` (legitly this time) :P

2023-11-06 14:44 UTC, ogp-weeloong commented on packages/backend/src/apps/index.ts
> +import CustomApiApp from './custom-api'
nit: camelCase

```suggestion
import customApiApp from './custom-api'
```

2023-11-07 10:59 UTC, liangyuanruo commented
Thanks @ogp-weeloong ; tested this PR for Forms, if-else, Vault, Telegram, Postman, Twilio.

2023-11-08 05:10 UTC, ogp-weeloong approved these changes
Ace A++++++++++ work, thanks so much for this!

2023-11-08 06:21 UTC, merged