PLU-125: [EXCEL] Find first table row action
opengovsg/plumber pull request #413
Opened 2024-01-26 03:39 UTC by ogp-weeloong

## Problem
Users need a way to look up a row from an excel table.

## Solution
Implement an action to do this. Typically, this is done in XLS using the `MATCH()` formula, but for our case, I chose to use a full table scan to save on queries. See comment in code for more details.

## Tests
After implementing this action + update table row action, I will feature freeze and start adding unit tests. 

- Check that the search works (i.e. the row it returns indeed has a column value which matches the configured input).
- Check that the returned row is the first row whose column matches the configured input.
- Check that it can match against blank cells.
- Check that it indeed fetches `MAX_ROW`s rows.
- Check that it errors out if the table is too large.
- Check that it errors out if the configured column is missing.

2024-01-26 05:02 UTC, ogp-weeloong commented on packages/backend/src/apps/m365-excel/actions/find-first-table-row/index.ts
> +    const tableRows = tableRowResponseSchema.parse(
Tested on a file with 10k rows and 100 columns; zod parsing perf hit was acceptable (~600ms for zod vs ~500ms compared to directly casting via generics; only ~100ms more).

2024-01-29 10:37 UTC, pregnantboy requested changes
Generally looks ok, just the display names.

Also, check that the pipe owner has access to the excel file when acquiring session for all actions

2024-01-29 10:37 UTC, pregnantboy commented on packages/backend/src/apps/m365-excel/actions/find-first-table-row/get-data-out-metadata.ts
> +        label: `"${datum.columnName}" Column`,
i dunno what was the conclusion between u and stacey

2024-01-29 10:37 UTC, pregnantboy commented on packages/backend/src/apps/m365-excel/actions/find-first-table-row/index.ts
> +        success: true,
foundRow

2024-01-29 11:47 UTC, ogp-weeloong commented
@pregnantboy Addressing these in a later PR due to rebase hell from refactoring in #414 . Updating this comment when I push out the PR.

2024-01-30 10:44 UTC, ogp-weeloong commented
Abandoning this and creating new PRs after feedback from PD. OTherwise too much to review.

2024-01-30 10:44 UTC, closed without merging