feat: refactor test run to not return error if test failed
opengovsg/plumber pull request #680
Opened 2024-07-27 07:10 UTC by pregnantboy

2024-07-27 07:10 UTC, pregnantboy commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/opengovsg/plumber/680?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#680** <a href="https://app.graphite.dev/github/pr/opengovsg/plumber/680?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#679** <a href="https://app.graphite.dev/github/pr/opengovsg/plumber/679?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#678** <a href="https://app.graphite.dev/github/pr/opengovsg/plumber/678?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `develop-v2`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @pregnantboy and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-06 03:24 UTC, m0nggh commented on packages/backend/src/services/test-run.ts
> +  await flow.$query().patch({
wait sorz is it me or this will never occur? should this be done at the start instead

2024-08-06 03:29 UTC, m0nggh requested changes
need to clarify one comment, will need to re-test again with the `test_execution_id`.

but tested without the `test_execution_id` column being filled and everything works as intended:
- `we couldn't find any test data` appears by default for untested steps
- clicking test run will update with the new variables
- refreshing the page will show the new updated executionstep
- error shows if test step fails
- previous error appears for current step regardless of whether it works

2024-08-20 09:34 UTC, m0nggh approved these changes
ok tested that it works now, lgtm

2024-08-27 10:30 UTC, pregnantboy commented
### Merge activity

* **Aug 27, 6:30 AM EDT**: @pregnantboy started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/opengovsg/plumber/680).

2024-08-27 10:54 UTC, merged