[
opengovsg/plumber pull request #793
Opened 2024-11-08 05:42 UTC by kevinkim-ogp

## Problem
Allow headers to be set using variables for Custom API.

Closes [insert issue #]

## Solution
Add option to set custom headers in the "Set up step" with ability to select variables.

<img width="859" alt="Screenshot 2024-11-08 at 12 13 56 PM" src="https://github.com/user-attachments/assets/56c3720e-2d88-432e-9505-24c144cc6919">

**Features**:
- Enable custom headers to be sent (on top of headers configured during "Add new connection")

- Implement multi column input to adopt similar input style as Postman/Bruno
<img width="851" alt="Screenshot 2024-11-08 at 1 33 24 PM" src="https://github.com/user-attachments/assets/c2194022-4457-4676-ab0d-25a297f10c26">

- 

## Before & After Screenshots

**BEFORE**:
- N/A. New feature

**AFTER**:
[insert screenshot here]
1. Custom Headers set on Plumber
<img width="850" alt="Screenshot 2024-11-08 at 1 41 21 PM" src="https://github.com/user-attachments/assets/f1e97f81-2c85-4e5a-9273-51d2ab45b4cd">
2. Custom Headers received
<img width="855" alt="Screenshot 2024-11-08 at 1 42 22 PM" src="https://github.com/user-attachments/assets/696e0305-aeeb-4183-bf93-eb43328a0120">
4. 
## Tests

_What tests should be run to confirm functionality?_

- [ ] Validate key-value pairs, i.e. key/value should not be null
- [ ] Custom headers should not override headers set up during the "Add new connection" stage
- [ ] 

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New scripts**:

- `packages/backend/src/apps/custom-api/actions/http-request/schema.ts` : validate custom headers
- `packages/frontend/src/components/MultiCol.tsx/index.tsx` : component for multi column input
- `packages/frontend/src/components/MultiRow/RowDivider.tsx` : move "And" divider to separate component

2024-11-12 12:45 UTC, pregnantboy requested changes
almost there 💪🏻

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +      customButtonText: 'Add',
```suggestion
      addRowButtonText: 'Add',
```

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +          customStyle: { flex: 0.5 },
too much code change for this. for now default all `multirow-multicol` fields to use this style. i dont see when this will not be applicable.

i.e. dont introduce `customStyle` property yet

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +      showDivider: false,
similarly remove this property. all multirow-multi-col should not show dividers

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/graphql/schema.graphql
> +  isSingleLine: Boolean
we should refrain from introducing too many new properties/flags unless we absolutely need.

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +      hideBlankRow: true,
this should be the default for this type of field if `required` is false

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +          isSingleLine: true,
likewise, find a way to remove this variable. for example, check that this field is part of a multirow input, if so, set to single line

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +          isSingleLine: true,
also, the text not vertically centered
![image](https://github.com/user-attachments/assets/80e51d90-53b5-4037-b41d-114a9a16747c)

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/schema.ts
> +        value: z.string().trim().min(1, 'Value empty'),
this should be optional. in the event when the substituted variables is empty, it should not fail

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/schema.ts
> +        value: z.string().trim().min(1, 'Value empty'),
otherwise, good job with the schema checks

2024-11-12 12:45 UTC, pregnantboy commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +      showOptionValue: false,
good catch

2024-11-12 12:45 UTC, pregnantboy commented on packages/frontend/src/components/MultiCol.tsx/index.tsx
> +          onClick={() => remove && remove(index)}
nit:
```suggestion
          onClick={() => remove?.(index)}
```

2024-11-12 12:45 UTC, pregnantboy commented on packages/frontend/src/components/MultiCol.tsx/index.tsx
> +          onClick={() => remove && remove(index)}
also, the delete button is not deleting the right row
e.g. if u delete row 2, row 3 gets deleted. i think is a display issue
<img width="885" alt="image" src="https://github.com/user-attachments/assets/2cc9bdd0-1b8e-4ff8-b383-585a5828c9ff">

2024-11-12 12:45 UTC, pregnantboy commented on packages/frontend/src/components/RichTextEditor/index.tsx
> +import React, { useCallback, useContext, useEffect, useMemo } from 'react'
why u import React

2024-11-13 10:13 UTC, kevinkim-ogp commented on packages/backend/src/apps/custom-api/actions/http-request/index.ts
> +      hideBlankRow: true,
current implementation in LetterSG has a default row shown cos usually will have some sort of personalised field to fill in. 
in the case where there is no personalised field to fill, the test step will fail if user doesn't delete the empty row.

at custom api, if we show the blank row by default and user does not want to use, they will need to manually delete. think most likely they wont bother to delete the empty row and try to test, which the test will fail then they need to go back to delete the empty row

<img width="856" alt="Screenshot 2024-11-13 at 6 08 24 PM" src="https://github.com/user-attachments/assets/e97dc8b2-7cb9-45ed-83c4-739edb708ada">

2024-11-13 13:50 UTC, kevinkim-ogp commented on packages/frontend/src/components/MultiCol.tsx/index.tsx
> +          onClick={() => remove && remove(index)}
for future ref: bug was caused by index being used as key, switched to id instead

2024-11-25 09:28 UTC, pregnantboy approved these changes
minor change then good to go

2024-11-25 09:28 UTC, pregnantboy commented on packages/backend/src/graphql/schema.graphql
> +  hideBlankRow: Boolean
depend on `required` to set this. also, change lettersg letterParams to required: true

2024-11-25 10:23 UTC, merged