fix: escape variables for custom-api data
opengovsg/plumber pull request #822
Opened 2024-12-18 01:12 UTC by kevinkim-ogp

fix: escape variables for custom-api data

refactor: clean up schema

2024-12-18 01:12 UTC, kevinkim-ogp commented
* **#823** <a href="https://app.graphite.dev/github/pr/opengovsg/plumber/823?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#822** <a href="https://app.graphite.dev/github/pr/opengovsg/plumber/822?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/opengovsg/plumber/822?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `develop-v2`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-19 06:54 UTC, pregnantboy requested changes
you can actually use the preprocessVariable hook in actions e.g.:

<img width="421" alt="image" src="https://github.com/user-attachments/assets/289509e1-c94d-4aab-ad12-3a2ce5cfd417" />

2024-12-23 07:49 UTC, pregnantboy approved these changes

2024-12-23 07:50 UTC, pregnantboy commented
### Merge activity

* **Dec 23, 2:50 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/opengovsg/plumber/822).

2024-12-23 07:54 UTC, merged